/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'miyasaka.yasumasa' at '17/02/20 22:18' with Gradle 2.14.1
 *
 * @author miyasaka.yasumasa, @date 17/02/20 22:18
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
