import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'miyasaka.yasumasa' at '17/02/20 22:18' with Gradle 2.14.1
 *
 * @author miyasaka.yasumasa, @date 17/02/20 22:18
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
